# RISC-V Assembly - Functions and Recursion# 演示函数调用、栈帧管理和递归    .section .text    .globl _start_start:
    # === 测试1: 简单函数调用 ===    addi a0, zero, 10        # 参数: n = 10    jal  ra, square          # 调用 square(10)    # 返回值在 a0 中 = 100    # === 测试2: 递归阶乘 ===    addi a0, zero, 5         # 参数: n = 5    jal  ra, factorial       # 调用 factorial(5)    # 返回值在 a0 中 = 120    # === 测试3: 递归斐波那契 ===    addi a0, zero, 10        # 参数: n = 10    jal  ra, fibonacci       # 调用 fibonacci(10)    # 返回值在 a0 中 = 55    # === 测试4: 栈的使用 ===    addi a0, zero, 3         # 参数: n = 3    addi a1, zero, 4         # 参数: m = 4    jal  ra, power           # 调用 power(3, 4)    # 返回值在 a0 中 = 81
    # === 程序结束 ===    end_loop:
    j    end_loop# ============================================# 函数: square (平方)# 参数: a0 = n# 返回: a0 = n^2
# ============================================square:    # 乘法通常需要M扩展    # 如果没有M扩展，可以用循环实现    mulw a0, a0, a0          # a0 = a0 * a0    ret                      # 返回# ============================================# 函数: factorial (阶乘)# 参数: a0 = n# 返回: a0 = n!# ============================================factorial:
    # === 栈帧设置 ===    addi sp, sp, -12         # 分配栈帧 (3个字)    sw   ra, 8(sp)           # 保存返回地址
    sw   s0, 4(sp)           # 保存保存寄存器    sw   s1, 0(sp)           # 保存另一个寄存器    # === 基本情况 ===    addi t0, zero, 1        # t0 = 1    ble  a0, t0, factorial_base  # if (n <= 1) return 1    # === 递归情况 ===    addi s0, a0, zero       # s0 = n (保存)    addi a0, a0, -1         # a0 = n - 1    jal  ra, factorial       # 递归调用 factorial(n-1)    # a0 现在包含 (n-1)!    mulw a0, s0, a0          # a0 = n * (n-1)!    j    factorial_donefactorial_base:    addi a0, zero, 1        # return 1factorial_done:    # === 栈帧恢复 ===    lw   s1, 0(sp)           # 恢复寄存器
    lw   s0, 4(sp)
    lw   ra, 8(sp)           # 恢复返回地址    addi sp, sp, 12          # 释放栈帧
    ret                      # 返回# ============================================# 函数: fibonacci (斐波那契)# 参数: a0 = n# 返回: a0 = fib(n)# ============================================fibonacci:    # === 栈帧设置 ===    addi sp, sp, -16         # 分配栈帧    sw   ra, 12(sp)          # 保存返回地址    sw   s0, 8(sp)           # 保存寄存器
    sw   s1, 4(sp)    sw   s2, 0(sp)    # === 基本情况 ===    addi t0, zero, 0        beq  a0, t0, fib_zero    addi t0, zero, 1    ble  a0, t0, fib_one    # === 递归情况 ===    addi s0, a0, zero       # s0 = n
    # 计算 fib(n-1)    addi a0, s0, -1         # a0 = n - 1    jal  ra, fibonacci       # fib(n-1)
    addi s1, a0, zero       # s1 = fib(n-1)    # 计算 fib(n-2)
    addi a0, s0, -2         # a0 = n - 2
    jal  ra, fibonacci       # fib(n-2)    addi s2, a0, zero       # s2 = fib(n-2)    # 返回 fib(n-1) + fib(n-2)    add  a0, s1, s2          # a0 = fib(n-1) + fib(n-2)    j    fibonacci_donefib_zero:    addi a0, zero, 0        # return 0    j    fibonacci_donefib_one:
    addi a0, zero, 1        # return 1fibonacci_done:    # === 栈帧恢复 ===    lw   s2, 0(sp)           # 恢复寄存器    lw   s1, 4(sp)
    lw   s0, 8(sp)    lw   ra, 12(sp)          # 恢复返回地址    addi sp, sp, 16          # 释放栈帧    ret                      # 返回# ============================================# 函数: power (幂运算)# 参数: a0 = base, a1 = exponent# 返回: a0 = base^exponent# ============================================power:    # === 栈帧设置 ===    addi sp, sp, -12         # 分配栈帧
    sw   ra, 8(sp)           # 保存返回地址    sw   s0, 4(sp)           # 保存寄存器    sw   s1, 0(sp)    # === 基本情况 ===    addi t0, zero, 1        beq  a1, t0, power_one   # if (exp == 1) return base    addi t0, zero, 0    beq  a1, t0, power_zero  # if (exp == 0) return 1    # === 递归情况 ===    addi s0, a0, zero       # s0 = base
    addi s1, a1, zero       # s1 = exp    # 递归: base^(exp-1)    addi a1, s1, -1         # a1 = exp - 1    jal  ra, power           # power(base, exp-1)    mulw a0, s0, a0          # a0 = base * power(base, exp-1)    j    power_donepower_one:
    # ra 已经保存    # a0 已经是 base    j    power_donepower_zero:    addi a0, zero, 1        # return 1power_done:
    # === 栈帧恢复 ===    lw   s1, 0(sp)           # 恢复寄存器    lw   s0, 4(sp)
    lw   ra, 8(sp)           # 恢复返回地址    addi sp, sp, 12          # 释放栈帧    ret                      # 返回# ============================================# 调用约定说明# ============================================## RISC-V 调用约定:# # 调用者保存: t0-t6, a0-a7, ra# 被调用者保存: s0-s11, sp# # 参数: a0-a7# 返回值: a0-a1# 返回地址: ra# 栈指针: sp# # 函数调用流程:# 1. 设置参数 (a0-a7)# 2. jal ra, function (调用并保存返回地址)# 3. 函数内部:#    - 保存调用者保存的寄存器到栈#    - 分配栈帧 (sp = sp - N)#    - 执行函数逻辑#    - 恢复寄存器#    - 释放栈帧#    - ret (返回)# ============================================# 练习任务:# 1. 添加更多的数学函数 (gcd, lcm等)# 2. 实现快速幂算法# 3. 实现快速排序的递归版本# 4. 理解并手动跟踪递归调用过程
