#!/usr/bin/env python3
"""Train a tiny 8x8 MNIST float32 classifier and export FPGA init data.

Model:
    score[class] = bias[class] + sum(pixel[i] * weight[class][i])

Pixels are binarized 8x8 values. The FPGA CPU runs the same computation with
custom fmul32/fadd32 instructions; this script only trains offline and emits
weights.
"""

from __future__ import annotations

import argparse
import json
import os
import struct
from pathlib import Path

import numpy as np
import torch
from PIL import Image
from torchvision.datasets import MNIST


ROOT = Path(__file__).resolve().parents[1]


def float_word(x: float) -> int:
    return struct.unpack("<I", struct.pack("<f", float(x)))[0]


def load_mnist8(root: Path, limit_train: int | None = None) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    train = MNIST(root=str(root), train=True, download=True)
    test = MNIST(root=str(root), train=False, download=True)

    def convert(ds, limit=None):
        n = len(ds) if limit is None else min(limit, len(ds))
        x = np.zeros((n, 64), dtype=np.float32)
        y = np.zeros((n,), dtype=np.int64)
        for i in range(n):
            img, label = ds[i]
            small = img.resize((8, 8), Image.Resampling.BILINEAR)
            arr = np.asarray(small, dtype=np.float32) / 255.0
            x[i] = (arr >= 0.25).astype(np.float32).reshape(-1)
            y[i] = label
        return x, y

    x_train, y_train = convert(train, limit_train)
    x_test, y_test = convert(test, None)
    return x_train, y_train, x_test, y_test


def train_linear(x_train, y_train, x_test, y_test, epochs: int, lr: float, seed: int):
    torch.manual_seed(seed)
    x = torch.from_numpy(x_train)
    y = torch.from_numpy(y_train)
    xt = torch.from_numpy(x_test)
    yt = torch.from_numpy(y_test)

    model = torch.nn.Linear(64, 10)
    opt = torch.optim.SGD(model.parameters(), lr=lr, momentum=0.9, weight_decay=1e-4)
    loss_fn = torch.nn.CrossEntropyLoss()
    batch = 512
    for epoch in range(epochs):
        perm = torch.randperm(x.shape[0])
        total = 0.0
        for start in range(0, x.shape[0], batch):
            idx = perm[start:start + batch]
            opt.zero_grad()
            loss = loss_fn(model(x[idx]), y[idx])
            loss.backward()
            opt.step()
            total += float(loss) * len(idx)
        with torch.no_grad():
            acc = (model(xt).argmax(dim=1) == yt).float().mean().item()
        print(f"epoch {epoch + 1:02d}: loss={total / x.shape[0]:.4f} test_acc={acc * 100:.2f}%")

    with torch.no_grad():
        train_acc = (model(x).argmax(dim=1) == y).float().mean().item()
        test_acc = (model(xt).argmax(dim=1) == yt).float().mean().item()
        w = model.weight.detach().cpu().numpy().astype(np.float32)
        b = model.bias.detach().cpu().numpy().astype(np.float32)
    return w, b, train_acc, test_acc


def class_prototypes(x_train: np.ndarray, y_train: np.ndarray) -> list[str]:
    out = []
    for d in range(10):
        avg = x_train[y_train == d].mean(axis=0)
        bits = (avg >= 0.35).astype(np.uint8)
        out.append("".join(str(int(v)) for v in bits))
    return out


def export_vh(path: Path, weights: np.ndarray, bias: np.ndarray, base_word: int = 64) -> None:
    # data_mem word layout:
    #   0..15       image bytes / scratch area
    #   64..703     weights[10][64]
    #   704..713    bias[10]
    #   714         float32 1.0
    lines = [
        "// generated by scripts/train_mnist8.py -- do not edit",
        "// data RAM float32 model: weights[10][64], bias[10], one",
    ]

    def emit_word(word_index: int, value: int, comment: str) -> None:
        b0 = value & 0xFF
        b1 = (value >> 8) & 0xFF
        b2 = (value >> 16) & 0xFF
        b3 = (value >> 24) & 0xFF
        lines.append(f"        data_mem_b0[{word_index:3d}] = 8'h{b0:02x}; data_mem_b1[{word_index:3d}] = 8'h{b1:02x}; data_mem_b2[{word_index:3d}] = 8'h{b2:02x}; data_mem_b3[{word_index:3d}] = 8'h{b3:02x}; // {comment}")

    idx = base_word
    for d in range(10):
        for i in range(64):
            emit_word(idx, float_word(weights[d, i]), f"w[{d}][{i}]")
            idx += 1
    for d in range(10):
        emit_word(idx, float_word(bias[d]), f"bias[{d}]")
        idx += 1
    emit_word(idx, float_word(1.0), "one")

    path.write_text("\n".join(lines) + "\n")


def export_json(path: Path, weights, bias, prototypes, train_acc, test_acc) -> None:
    data = {
        "format": "mnist8-linear-float32",
        "train_accuracy": train_acc,
        "test_accuracy": test_acc,
        "weights_shape": [10, 64],
        "bias_shape": [10],
        "prototypes": prototypes,
        "weights": weights.astype(float).tolist(),
        "bias": bias.astype(float).tolist(),
    }
    path.write_text(json.dumps(data, indent=2))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", default=str(ROOT / "data"))
    ap.add_argument("--vh", default=str(ROOT / "src" / "cnn_weights.vh"))
    ap.add_argument("--json", default=str(ROOT / "data" / "mnist8_model.json"))
    ap.add_argument("--epochs", type=int, default=12)
    ap.add_argument("--lr", type=float, default=0.5)
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--limit-train", type=int, default=60000)
    args = ap.parse_args()

    data_dir = Path(args.data_dir)
    data_dir.mkdir(parents=True, exist_ok=True)
    x_train, y_train, x_test, y_test = load_mnist8(data_dir, args.limit_train)
    w, b, train_acc, test_acc = train_linear(x_train, y_train, x_test, y_test, args.epochs, args.lr, args.seed)
    prototypes = class_prototypes(x_train, y_train)

    export_vh(Path(args.vh), w, b)
    export_json(Path(args.json), w, b, prototypes, train_acc, test_acc)
    print(f"wrote {args.vh}")
    print(f"wrote {args.json}")
    print(f"final train_acc={train_acc * 100:.2f}% test_acc={test_acc * 100:.2f}%")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
